global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nsq'
    static_configs:
      - targets: ['nsqd:4151', 'nsqlookupd:4161']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
